baseURL = ""
title = "Thomas MARTIN"

theme = "hugo-coder"

languageCode = "fr"
defaultContentLanguage = "fr"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "thomasmrtn"

[params]
    author = "Thomas Martin"
    description = "My personal website"
    keywords = "blog,dreamer,personal"
    info = "Hicker, Maker, Dreamer"
    avatarURL = "images/avatar.jpg"

    dateFormat = "January 2, 2006"

    hideFooter = true
    hideCredits = true
    hideCopyright = true
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
    token = "token"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram"
    weight = 1
    url = "https://www.instagram.com/thmartin/"  
  
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 3
    url = "https://github.com/thomasmrt"

[[params.social]]
    name = "Strava"
    icon = "fab fa-strava"
    weight = 2
    url = "https://www.strava.com/athletes/5070956"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/johndoe/"





[menu]


	[[menu.main]]
	name = "Trips"
	weight = 3
	url = "trips/"

	[[menu.main]]
	name = "DIY projects"
	weight = 5
	url = "projects/"
